// This file is auto-generated by @hey-api/openapi-ts

export const BoardCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        visibility: {
            '$ref': '#/components/schemas/Visibility',
            default: 'workspace'
        },
        background_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Background Image'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        },
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        }
    },
    type: 'object',
    required: ['name', 'workspace_id'],
    title: 'BoardCreate'
} as const;

export const BoardPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        visibility: {
            '$ref': '#/components/schemas/Visibility',
            default: 'workspace'
        },
        background_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Background Image'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        is_deleted: {
            type: 'boolean',
            title: 'Is Deleted',
            default: false
        }
    },
    type: 'object',
    required: ['name', 'id', 'workspace_id', 'owner_id'],
    title: 'BoardPublic'
} as const;

export const BoardUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        visibility: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Visibility'
                },
                {
                    type: 'null'
                }
            ]
        },
        background_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Background Image'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        }
    },
    type: 'object',
    title: 'BoardUpdate'
} as const;

export const BoardsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BoardPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BoardsPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CardCommentCreateSchema = {
    properties: {
        content: {
            type: 'string',
            maxLength: 5000,
            minLength: 1,
            title: 'Content'
        },
        card_id: {
            type: 'string',
            format: 'uuid',
            title: 'Card Id'
        }
    },
    type: 'object',
    required: ['content', 'card_id'],
    title: 'CardCommentCreate'
} as const;

export const CardCommentUpdateSchema = {
    properties: {
        content: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        }
    },
    type: 'object',
    title: 'CardCommentUpdate'
} as const;

export const CardCommentWithUserSchema = {
    properties: {
        content: {
            type: 'string',
            maxLength: 5000,
            minLength: 1,
            title: 'Content'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        card_id: {
            type: 'string',
            format: 'uuid',
            title: 'Card Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        is_deleted: {
            type: 'boolean',
            title: 'Is Deleted',
            default: false
        },
        user_full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Full Name'
        },
        user_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Email'
        }
    },
    type: 'object',
    required: ['content', 'id', 'card_id', 'user_id', 'created_at', 'updated_at'],
    title: 'CardCommentWithUser'
} as const;

export const CardCommentsWithUserPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CardCommentWithUser'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CardCommentsWithUserPublic'
} as const;

export const CardCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        position: {
            type: 'number',
            title: 'Position',
            default: 65535
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        },
        cover_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image'
        },
        list_id: {
            type: 'string',
            format: 'uuid',
            title: 'List Id'
        }
    },
    type: 'object',
    required: ['title', 'list_id'],
    title: 'CardCreate'
} as const;

export const CardPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        position: {
            type: 'number',
            title: 'Position',
            default: 65535
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        },
        cover_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        list_id: {
            type: 'string',
            format: 'uuid',
            title: 'List Id'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        is_deleted: {
            type: 'boolean',
            title: 'Is Deleted',
            default: false
        }
    },
    type: 'object',
    required: ['title', 'id', 'list_id', 'created_at', 'updated_at'],
    title: 'CardPublic'
} as const;

export const CardUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        position: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        list_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'List Id'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        },
        cover_image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cover Image'
        }
    },
    type: 'object',
    title: 'CardUpdate'
} as const;

export const CardsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CardPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CardsPublic'
} as const;

export const ChecklistItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Title'
        },
        is_completed: {
            type: 'boolean',
            title: 'Is Completed',
            default: false
        },
        position: {
            type: 'number',
            title: 'Position',
            default: 65535
        },
        card_id: {
            type: 'string',
            format: 'uuid',
            title: 'Card Id'
        }
    },
    type: 'object',
    required: ['title', 'card_id'],
    title: 'ChecklistItemCreate'
} as const;

export const ChecklistItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Title'
        },
        is_completed: {
            type: 'boolean',
            title: 'Is Completed',
            default: false
        },
        position: {
            type: 'number',
            title: 'Position',
            default: 65535
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        card_id: {
            type: 'string',
            format: 'uuid',
            title: 'Card Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        is_deleted: {
            type: 'boolean',
            title: 'Is Deleted',
            default: false
        }
    },
    type: 'object',
    required: ['title', 'id', 'card_id', 'created_at', 'updated_at'],
    title: 'ChecklistItemPublic'
} as const;

export const ChecklistItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        is_completed: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Completed'
        },
        position: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        }
    },
    type: 'object',
    title: 'ChecklistItemUpdate'
} as const;

export const ChecklistItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ChecklistItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ChecklistItemsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InvitationStatusSchema = {
    type: 'string',
    enum: ['pending', 'accepted', 'rejected', 'expired'],
    title: 'InvitationStatus',
    description: 'Status of workspace invitation'
} as const;

export const ListCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        position: {
            type: 'number',
            title: 'Position',
            default: 65535
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        },
        board_id: {
            type: 'string',
            format: 'uuid',
            title: 'Board Id'
        }
    },
    type: 'object',
    required: ['name', 'board_id'],
    title: 'ListCreate'
} as const;

export const ListPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        position: {
            type: 'number',
            title: 'Position',
            default: 65535
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        board_id: {
            type: 'string',
            format: 'uuid',
            title: 'Board Id'
        },
        is_deleted: {
            type: 'boolean',
            title: 'Is Deleted',
            default: false
        }
    },
    type: 'object',
    required: ['name', 'id', 'board_id'],
    title: 'ListPublic'
} as const;

export const ListUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        position: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        }
    },
    type: 'object',
    title: 'ListUpdate'
} as const;

export const ListsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ListPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ListsPublic'
} as const;

export const MemberRoleSchema = {
    type: 'string',
    enum: ['admin', 'member', 'observer'],
    title: 'MemberRole'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NotificationPublicSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/NotificationType'
        },
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        message: {
            type: 'string',
            maxLength: 1000,
            title: 'Message'
        },
        is_read: {
            type: 'boolean',
            title: 'Is Read',
            default: false
        },
        reference_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference Id'
        },
        reference_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference Type'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['type', 'title', 'message', 'id', 'user_id', 'created_at'],
    title: 'NotificationPublic'
} as const;

export const NotificationTypeSchema = {
    type: 'string',
    enum: ['workspace_invitation', 'invitation_accepted', 'invitation_rejected', 'comment_added', 'card_assigned', 'card_due_soon', 'mentioned'],
    title: 'NotificationType',
    description: 'Types of notifications'
} as const;

export const NotificationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NotificationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        unread_count: {
            type: 'integer',
            title: 'Unread Count'
        }
    },
    type: 'object',
    required: ['data', 'count', 'unread_count'],
    title: 'NotificationsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        is_deleted: {
            type: 'boolean',
            title: 'Is Deleted',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VisibilitySchema = {
    type: 'string',
    enum: ['private', 'workspace', 'public'],
    title: 'Visibility'
} as const;

export const WorkspaceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        }
    },
    type: 'object',
    required: ['name'],
    title: 'WorkspaceCreate'
} as const;

export const WorkspaceInvitationCreateSchema = {
    properties: {
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        },
        invitee_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invitee Email'
        },
        invitee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invitee Id'
        },
        role: {
            '$ref': '#/components/schemas/MemberRole',
            default: 'member'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        }
    },
    type: 'object',
    required: ['workspace_id'],
    title: 'WorkspaceInvitationCreate',
    description: 'Create invitation by email or user_id'
} as const;

export const WorkspaceInvitationPublicSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/MemberRole',
            default: 'member'
        },
        status: {
            '$ref': '#/components/schemas/InvitationStatus',
            default: 'pending'
        },
        message: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        },
        inviter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Inviter Id'
        },
        invitee_id: {
            type: 'string',
            format: 'uuid',
            title: 'Invitee Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        responded_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Responded At'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['id', 'workspace_id', 'inviter_id', 'invitee_id', 'created_at', 'responded_at', 'expires_at'],
    title: 'WorkspaceInvitationPublic'
} as const;

export const WorkspaceInvitationRespondSchema = {
    properties: {
        accept: {
            type: 'boolean',
            title: 'Accept'
        }
    },
    type: 'object',
    required: ['accept'],
    title: 'WorkspaceInvitationRespond',
    description: 'Accept or reject an invitation'
} as const;

export const WorkspaceInvitationWithDetailsSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/MemberRole',
            default: 'member'
        },
        status: {
            '$ref': '#/components/schemas/InvitationStatus',
            default: 'pending'
        },
        message: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        },
        inviter_id: {
            type: 'string',
            format: 'uuid',
            title: 'Inviter Id'
        },
        invitee_id: {
            type: 'string',
            format: 'uuid',
            title: 'Invitee Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        responded_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Responded At'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        workspace_name: {
            type: 'string',
            title: 'Workspace Name'
        },
        inviter_name: {
            type: 'string',
            title: 'Inviter Name'
        },
        inviter_email: {
            type: 'string',
            title: 'Inviter Email'
        }
    },
    type: 'object',
    required: ['id', 'workspace_id', 'inviter_id', 'invitee_id', 'created_at', 'responded_at', 'expires_at', 'workspace_name', 'inviter_name', 'inviter_email'],
    title: 'WorkspaceInvitationWithDetails',
    description: 'Invitation with workspace and inviter names for display'
} as const;

export const WorkspaceInvitationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkspaceInvitationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkspaceInvitationsPublic'
} as const;

export const WorkspaceInviteSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        role: {
            '$ref': '#/components/schemas/MemberRole',
            default: 'member'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'WorkspaceInvite'
} as const;

export const WorkspaceMemberCreateSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        },
        role: {
            '$ref': '#/components/schemas/MemberRole',
            default: 'member'
        }
    },
    type: 'object',
    required: ['user_id', 'workspace_id'],
    title: 'WorkspaceMemberCreate'
} as const;

export const WorkspaceMemberPublicSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/MemberRole',
            default: 'member'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'workspace_id', 'created_at'],
    title: 'WorkspaceMemberPublic'
} as const;

export const WorkspaceMemberUpdateSchema = {
    properties: {
        role: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MemberRole'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'WorkspaceMemberUpdate'
} as const;

export const WorkspaceMembersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkspaceMemberPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkspaceMembersPublic'
} as const;

export const WorkspacePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        is_deleted: {
            type: 'boolean',
            title: 'Is Deleted',
            default: false
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id', 'created_at'],
    title: 'WorkspacePublic'
} as const;

export const WorkspaceUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_archived: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Archived'
        }
    },
    type: 'object',
    title: 'WorkspaceUpdate'
} as const;

export const WorkspacesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkspacePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkspacesPublic'
} as const;