// This file is auto-generated by @hey-api/openapi-ts

export type Board = {
    name: string;
    visibility?: Visibility;
    background_image?: (string | null);
    id?: string;
    workspace_id: string;
    owner_id: string;
};

export type BoardCreate = {
    name: string;
    visibility?: Visibility;
    background_image?: (string | null);
    workspace_id: string;
};

export type BoardPublic = {
    name: string;
    visibility?: Visibility;
    background_image?: (string | null);
    id: string;
    workspace_id: string;
    owner_id: string;
};

export type BoardsPublic = {
    data: Array<BoardPublic>;
    count: number;
};

export type BoardUpdate = {
    name?: (string | null);
    visibility?: (Visibility | null);
    background_image?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Card = {
    title: string;
    description?: (string | null);
    position?: number;
    due_date?: (string | null);
    is_archived?: boolean;
    cover_image?: (string | null);
    id?: string;
    list_id: string;
    created_at?: string;
    updated_at?: string;
};

export type CardCreate = {
    title: string;
    description?: (string | null);
    position?: number;
    due_date?: (string | null);
    is_archived?: boolean;
    cover_image?: (string | null);
    list_id: string;
};

export type CardPublic = {
    title: string;
    description?: (string | null);
    position?: number;
    due_date?: (string | null);
    is_archived?: boolean;
    cover_image?: (string | null);
    id: string;
    list_id: string;
    created_at: string;
    updated_at: string;
};

export type CardsPublic = {
    data: Array<CardPublic>;
    count: number;
};

export type CardUpdate = {
    title?: (string | null);
    description?: (string | null);
    position?: (number | null);
    due_date?: (string | null);
    is_archived?: (boolean | null);
    cover_image?: (string | null);
    list_id?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ListCreate = {
    name: string;
    position?: number;
    board_id: string;
};

export type ListPublic = {
    name: string;
    position?: number;
    id: string;
    board_id: string;
};

export type ListsPublic = {
    data: Array<ListPublic>;
    count: number;
};

export type ListUpdate = {
    name?: (string | null);
    position?: (number | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type Visibility = 'private' | 'workspace' | 'public';

export type WorkspaceCreate = {
    name: string;
    description?: (string | null);
};

export type WorkspacePublic = {
    name: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
};

export type WorkspacesPublic = {
    data: Array<WorkspacePublic>;
    count: number;
};

export type WorkspaceUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type BoardsReadBoardsData = {
    limit?: number;
    skip?: number;
};

export type BoardsReadBoardsResponse = (BoardsPublic);

export type BoardsCreateBoardData = {
    requestBody: BoardCreate;
};

export type BoardsCreateBoardResponse = (Board);

export type BoardsReadBoardData = {
    id: string;
};

export type BoardsReadBoardResponse = (Board);

export type BoardsUpdateBoardData = {
    id: string;
    requestBody: BoardUpdate;
};

export type BoardsUpdateBoardResponse = (Board);

export type BoardsDeleteBoardData = {
    id: string;
};

export type BoardsDeleteBoardResponse = (Message);

export type CardsReadCardsData = {
    limit?: number;
    skip?: number;
};

export type CardsReadCardsResponse = (CardsPublic);

export type CardsCreateCardData = {
    requestBody: CardCreate;
};

export type CardsCreateCardResponse = (Card);

export type CardsReadCardData = {
    id: string;
};

export type CardsReadCardResponse = (Card);

export type CardsUpdateCardData = {
    id: string;
    requestBody: CardUpdate;
};

export type CardsUpdateCardResponse = (Card);

export type CardsDeleteCardData = {
    id: string;
};

export type CardsDeleteCardResponse = (Message);

export type ListsReadBoardListsData = {
    limit?: number;
    skip?: number;
};

export type ListsReadBoardListsResponse = (ListsPublic);

export type ListsCreateBoardListData = {
    requestBody: ListCreate;
};

export type ListsCreateBoardListResponse = (ListPublic);

export type ListsReadBoardListData = {
    id: string;
};

export type ListsReadBoardListResponse = (ListPublic);

export type ListsUpdateBoardListData = {
    id: string;
    requestBody: ListUpdate;
};

export type ListsUpdateBoardListResponse = (ListPublic);

export type ListsDeleteBoardListData = {
    id: string;
};

export type ListsDeleteBoardListResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WorkspacesReadWorkspacesData = {
    limit?: number;
    skip?: number;
};

export type WorkspacesReadWorkspacesResponse = (WorkspacesPublic);

export type WorkspacesCreateWorkspaceData = {
    requestBody: WorkspaceCreate;
};

export type WorkspacesCreateWorkspaceResponse = (WorkspacesPublic);

export type WorkspacesReadWorkspaceData = {
    id: string;
};

export type WorkspacesReadWorkspaceResponse = (WorkspacesPublic);

export type WorkspacesUpdateWorkspaceData = {
    id: string;
    requestBody: WorkspaceUpdate;
};

export type WorkspacesUpdateWorkspaceResponse = (WorkspacesPublic);

export type WorkspacesDeleteWorkspaceData = {
    id: string;
};

export type WorkspacesDeleteWorkspaceResponse = (Message);