// This file is auto-generated by @hey-api/openapi-ts

export type BoardCreate = {
    name: string;
    visibility?: Visibility;
    background_image?: (string | null);
    is_archived?: boolean;
    workspace_id: string;
};

export type BoardPublic = {
    name: string;
    visibility?: Visibility;
    background_image?: (string | null);
    is_archived?: boolean;
    id: string;
    workspace_id: string;
    owner_id: string;
    is_deleted?: boolean;
};

export type BoardsPublic = {
    data: Array<BoardPublic>;
    count: number;
};

export type BoardUpdate = {
    name?: (string | null);
    visibility?: (Visibility | null);
    background_image?: (string | null);
    is_archived?: boolean;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CardCommentCreate = {
    content: string;
    card_id: string;
};

export type CardCommentsWithUserPublic = {
    data: Array<CardCommentWithUser>;
    count: number;
};

export type CardCommentUpdate = {
    content?: (string | null);
};

export type CardCommentWithUser = {
    content: string;
    id: string;
    card_id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
    is_deleted?: boolean;
    user_full_name?: (string | null);
    user_email?: (string | null);
};

export type CardCreate = {
    title: string;
    description?: (string | null);
    position?: number;
    due_date?: (string | null);
    is_archived?: boolean;
    cover_image?: (string | null);
    list_id: string;
};

export type CardPublic = {
    title: string;
    description?: (string | null);
    position?: number;
    due_date?: (string | null);
    is_archived?: boolean;
    cover_image?: (string | null);
    id: string;
    list_id: string;
    created_by?: (string | null);
    created_at: string;
    updated_at: string;
    is_deleted?: boolean;
};

export type CardsPublic = {
    data: Array<CardPublic>;
    count: number;
};

export type CardUpdate = {
    title?: (string | null);
    description?: (string | null);
    position?: (number | null);
    list_id?: (string | null);
    due_date?: (string | null);
    is_archived?: (boolean | null);
    cover_image?: (string | null);
};

export type ChecklistItemCreate = {
    title: string;
    is_completed?: boolean;
    position?: number;
    card_id: string;
};

export type ChecklistItemPublic = {
    title: string;
    is_completed?: boolean;
    position?: number;
    id: string;
    card_id: string;
    created_at: string;
    updated_at: string;
    is_deleted?: boolean;
};

export type ChecklistItemsPublic = {
    data: Array<ChecklistItemPublic>;
    count: number;
};

export type ChecklistItemUpdate = {
    title?: (string | null);
    is_completed?: (boolean | null);
    position?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Status of workspace invitation
 */
export type InvitationStatus = 'pending' | 'accepted' | 'rejected' | 'expired';

export type ListCreate = {
    name: string;
    position?: number;
    is_archived?: boolean;
    board_id: string;
};

export type ListPublic = {
    name: string;
    position?: number;
    is_archived?: boolean;
    id: string;
    board_id: string;
    is_deleted?: boolean;
};

export type ListsPublic = {
    data: Array<ListPublic>;
    count: number;
};

export type ListUpdate = {
    name?: (string | null);
    position?: (number | null);
    is_archived?: boolean;
};

export type MemberRole = 'admin' | 'member' | 'observer';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationPublic = {
    type: NotificationType;
    title: string;
    message: string;
    is_read?: boolean;
    reference_id?: (string | null);
    reference_type?: (string | null);
    id: string;
    user_id: string;
    created_at: string;
};

export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
    unread_count: number;
};

/**
 * Types of notifications
 */
export type NotificationType = 'workspace_invitation' | 'invitation_accepted' | 'invitation_rejected' | 'comment_added' | 'card_assigned' | 'card_due_soon' | 'mentioned';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    is_deleted?: boolean;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type Visibility = 'private' | 'workspace' | 'public';

export type WorkspaceCreate = {
    name: string;
    description?: (string | null);
    is_archived?: boolean;
};

/**
 * Create invitation by email or user_id
 */
export type WorkspaceInvitationCreate = {
    workspace_id: string;
    invitee_email?: (string | null);
    invitee_id?: (string | null);
    role?: MemberRole;
    message?: (string | null);
};

export type WorkspaceInvitationPublic = {
    role?: MemberRole;
    status?: InvitationStatus;
    message?: (string | null);
    id: string;
    workspace_id: string;
    inviter_id: string;
    invitee_id: string;
    created_at: string;
    responded_at: (string | null);
    expires_at: (string | null);
};

/**
 * Accept or reject an invitation
 */
export type WorkspaceInvitationRespond = {
    accept: boolean;
};

export type WorkspaceInvitationsPublic = {
    data: Array<WorkspaceInvitationPublic>;
    count: number;
};

/**
 * Invitation with workspace and inviter names for display
 */
export type WorkspaceInvitationWithDetails = {
    role?: MemberRole;
    status?: InvitationStatus;
    message?: (string | null);
    id: string;
    workspace_id: string;
    inviter_id: string;
    invitee_id: string;
    created_at: string;
    responded_at: (string | null);
    expires_at: (string | null);
    workspace_name: string;
    inviter_name: string;
    inviter_email: string;
};

export type WorkspaceInvite = {
    email: string;
    role?: MemberRole;
};

export type WorkspaceMemberCreate = {
    user_id: string;
    workspace_id: string;
    role?: MemberRole;
};

export type WorkspaceMemberPublic = {
    role?: MemberRole;
    id: string;
    user_id: string;
    workspace_id: string;
    created_at: string;
};

export type WorkspaceMembersPublic = {
    data: Array<WorkspaceMemberPublic>;
    count: number;
};

export type WorkspaceMemberUpdate = {
    role?: (MemberRole | null);
};

export type WorkspacePublic = {
    name: string;
    description?: (string | null);
    is_archived?: boolean;
    id: string;
    owner_id: string;
    created_at: string;
    is_deleted?: boolean;
};

export type WorkspacesPublic = {
    data: Array<WorkspacePublic>;
    count: number;
};

export type WorkspaceUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_archived?: (boolean | null);
};

export type BoardsReadBoardsData = {
    limit?: number;
    skip?: number;
};

export type BoardsReadBoardsResponse = (BoardsPublic);

export type BoardsCreateBoardData = {
    requestBody: BoardCreate;
};

export type BoardsCreateBoardResponse = (BoardPublic);

export type BoardsReadBoardData = {
    id: string;
};

export type BoardsReadBoardResponse = (BoardPublic);

export type BoardsUpdateBoardData = {
    id: string;
    requestBody: BoardUpdate;
};

export type BoardsUpdateBoardResponse = (BoardPublic);

export type BoardsDeleteBoardData = {
    id: string;
};

export type BoardsDeleteBoardResponse = (Message);

export type CardsReadCardsData = {
    limit?: number;
    skip?: number;
};

export type CardsReadCardsResponse = (CardsPublic);

export type CardsCreateCardData = {
    requestBody: CardCreate;
};

export type CardsCreateCardResponse = (CardPublic);

export type CardsReadCardData = {
    id: string;
};

export type CardsReadCardResponse = (CardPublic);

export type CardsUpdateCardData = {
    id: string;
    requestBody: CardUpdate;
};

export type CardsUpdateCardResponse = (CardPublic);

export type CardsDeleteCardData = {
    id: string;
};

export type CardsDeleteCardResponse = (Message);

export type CardsMoveCardData = {
    id: string;
    listId: string;
    position: number;
};

export type CardsMoveCardResponse = (CardPublic);

export type ChecklistsReadChecklistItemsData = {
    cardId?: (string | null);
    limit?: number;
    skip?: number;
};

export type ChecklistsReadChecklistItemsResponse = (ChecklistItemsPublic);

export type ChecklistsCreateChecklistItemData = {
    requestBody: ChecklistItemCreate;
};

export type ChecklistsCreateChecklistItemResponse = (ChecklistItemPublic);

export type ChecklistsReadChecklistItemData = {
    id: string;
};

export type ChecklistsReadChecklistItemResponse = (ChecklistItemPublic);

export type ChecklistsUpdateChecklistItemData = {
    id: string;
    requestBody: ChecklistItemUpdate;
};

export type ChecklistsUpdateChecklistItemResponse = (ChecklistItemPublic);

export type ChecklistsDeleteChecklistItemData = {
    id: string;
};

export type ChecklistsDeleteChecklistItemResponse = ({
    [key: string]: unknown;
});

export type ChecklistsToggleChecklistItemData = {
    id: string;
};

export type ChecklistsToggleChecklistItemResponse = (ChecklistItemPublic);

export type CommentsReadCommentsData = {
    cardId?: (string | null);
    limit?: number;
    skip?: number;
};

export type CommentsReadCommentsResponse = (CardCommentsWithUserPublic);

export type CommentsCreateCommentData = {
    requestBody: CardCommentCreate;
};

export type CommentsCreateCommentResponse = (CardCommentWithUser);

export type CommentsReadCommentData = {
    id: string;
};

export type CommentsReadCommentResponse = (CardCommentWithUser);

export type CommentsUpdateCommentData = {
    id: string;
    requestBody: CardCommentUpdate;
};

export type CommentsUpdateCommentResponse = (CardCommentWithUser);

export type CommentsDeleteCommentData = {
    id: string;
};

export type CommentsDeleteCommentResponse = ({
    [key: string]: unknown;
});

export type InvitationsReadMyInvitationsData = {
    status?: (InvitationStatus | null);
};

export type InvitationsReadMyInvitationsResponse = (Array<WorkspaceInvitationWithDetails>);

export type InvitationsCreateInvitationData = {
    requestBody: WorkspaceInvitationCreate;
};

export type InvitationsCreateInvitationResponse = (WorkspaceInvitationPublic);

export type InvitationsReadSentInvitationsData = {
    workspaceId?: (string | null);
};

export type InvitationsReadSentInvitationsResponse = (WorkspaceInvitationsPublic);

export type InvitationsRespondToInvitationData = {
    id: string;
    requestBody: WorkspaceInvitationRespond;
};

export type InvitationsRespondToInvitationResponse = (WorkspaceInvitationPublic);

export type InvitationsCancelInvitationData = {
    id: string;
};

export type InvitationsCancelInvitationResponse = (Message);

export type ListsReadBoardListsData = {
    limit?: number;
    skip?: number;
};

export type ListsReadBoardListsResponse = (ListsPublic);

export type ListsCreateBoardListData = {
    requestBody: ListCreate;
};

export type ListsCreateBoardListResponse = (ListPublic);

export type ListsReadListsByBoardData = {
    boardId: string;
};

export type ListsReadListsByBoardResponse = (ListsPublic);

export type ListsReadBoardListData = {
    id: string;
};

export type ListsReadBoardListResponse = (ListPublic);

export type ListsUpdateBoardListData = {
    id: string;
    requestBody: ListUpdate;
};

export type ListsUpdateBoardListResponse = (ListPublic);

export type ListsDeleteBoardListData = {
    id: string;
};

export type ListsDeleteBoardListResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NotificationsReadNotificationsData = {
    limit?: number;
    skip?: number;
    unreadOnly?: boolean;
};

export type NotificationsReadNotificationsResponse = (NotificationsPublic);

export type NotificationsGetUnreadCountResponse = ({
    [key: string]: unknown;
});

export type NotificationsReadNotificationData = {
    id: string;
};

export type NotificationsReadNotificationResponse = (NotificationPublic);

export type NotificationsDeleteNotificationData = {
    id: string;
};

export type NotificationsDeleteNotificationResponse = (Message);

export type NotificationsMarkAsReadData = {
    id: string;
};

export type NotificationsMarkAsReadResponse = (NotificationPublic);

export type NotificationsMarkAllAsReadResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WorkspacesReadWorkspacesData = {
    limit?: number;
    skip?: number;
};

export type WorkspacesReadWorkspacesResponse = (WorkspacesPublic);

export type WorkspacesCreateWorkspaceData = {
    requestBody: WorkspaceCreate;
};

export type WorkspacesCreateWorkspaceResponse = (WorkspacePublic);

export type WorkspacesReadWorkspaceData = {
    id: string;
};

export type WorkspacesReadWorkspaceResponse = (WorkspacePublic);

export type WorkspacesUpdateWorkspaceData = {
    id: string;
    requestBody: WorkspaceUpdate;
};

export type WorkspacesUpdateWorkspaceResponse = (WorkspacePublic);

export type WorkspacesDeleteWorkspaceData = {
    id: string;
};

export type WorkspacesDeleteWorkspaceResponse = (Message);

export type WorkspacesReadWorkspaceMembersData = {
    id: string;
};

export type WorkspacesReadWorkspaceMembersResponse = (WorkspaceMembersPublic);

export type WorkspacesAddWorkspaceMemberData = {
    id: string;
    requestBody: WorkspaceMemberCreate;
};

export type WorkspacesAddWorkspaceMemberResponse = (WorkspaceMemberPublic);

export type WorkspacesInviteWorkspaceMemberData = {
    id: string;
    requestBody: WorkspaceInvite;
};

export type WorkspacesInviteWorkspaceMemberResponse = (WorkspaceMemberPublic);

export type WorkspacesUpdateWorkspaceMemberData = {
    id: string;
    memberId: string;
    requestBody: WorkspaceMemberUpdate;
};

export type WorkspacesUpdateWorkspaceMemberResponse = (WorkspaceMemberPublic);

export type WorkspacesRemoveWorkspaceMemberData = {
    id: string;
    memberId: string;
};

export type WorkspacesRemoveWorkspaceMemberResponse = (Message);