"""add_notifications_invitations_card_created_by

Revision ID: 05cf83a9a367
Revises: 2c1235850db5
Create Date: 2025-12-15 17:43:19.456591

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '05cf83a9a367'
down_revision = '2c1235850db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('type', sa.Enum('workspace_invitation', 'invitation_accepted', 'invitation_rejected', 'comment_added', 'card_assigned', 'card_due_soon', 'mentioned', name='notificationtype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('workspace_invitation',
    sa.Column('role', sa.Enum('admin', 'member', 'observer', name='memberrole'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'expired', name='invitationstatus'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('inviter_id', sa.Uuid(), nullable=False),
    sa.Column('invitee_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_invitation_invitee_id'), 'workspace_invitation', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_workspace_invitation_workspace_id'), 'workspace_invitation', ['workspace_id'], unique=False)
    op.add_column('card', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'card', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'created_by')
    op.drop_index(op.f('ix_workspace_invitation_workspace_id'), table_name='workspace_invitation')
    op.drop_index(op.f('ix_workspace_invitation_invitee_id'), table_name='workspace_invitation')
    op.drop_table('workspace_invitation')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
