"""add_soft_delete_to_user

Revision ID: 2c1235850db5
Revises: a81fb423df9d
Create Date: 2025-12-15 17:12:31.403354

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2c1235850db5'
down_revision = 'a81fb423df9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_column('user', 'deleted_by')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'is_deleted')
    # ### end Alembic commands ###
